### ISSUE TITLE
Installation fails if f77 not installed

### ISSUE THREAD

**Issue by tycohen** [v-morello/pyne2001#2] opened 2021-02-01 19:25 UTC
Full traceback
```
pip install -e .
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///users/tcohen/python/projects/pyne2001
Installing collected packages: pyne2001
  Attempting uninstall: pyne2001
    Found existing installation: pyne2001 0.1.3
    Can't uninstall 'pyne2001'. No files were found to uninstall.
  Running setup.py develop for pyne2001
    ERROR: Command errored out with exit status 1:
     command: /users/tcohen/miniconda2/envs/pulsar/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/users/tcohen/python/projects/pyne2001/setup.py'"'"'; __file__='"'"'/users/tcohen/python/projects/pyne2001/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /users/tcohen/python/projects/pyne2001/
    Complete output (28 lines):
    running develop
    make[1]: Entering directory `/users/tcohen/python/projects/pyne2001/pyne2001/NE2001/src'
    rm -f ../bin/NE2001 NE2001.o dmdsm.NE2001.o density.NE2001.o neLISM.NE2001.o neclumpN.o nevoidN.o scattering98.o libNE2001.a
    make[1]: Leaving directory `/users/tcohen/python/projects/pyne2001/pyne2001/NE2001/src'
    make[1]: Entering directory `/users/tcohen/python/projects/pyne2001/pyne2001/NE2001/src'
    f77 -O -std=gnu  -c -o NE2001.o NE2001.f
    make[1]: f77: Command not found
    make[1]: *** [NE2001.o] Error 127
    make[1]: Leaving directory `/users/tcohen/python/projects/pyne2001/pyne2001/NE2001/src'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/users/tcohen/python/projects/pyne2001/setup.py", line 97, in <module>
        'build_py': CustomBuildPy
      File "/users/tcohen/miniconda2/envs/pulsar/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/users/tcohen/miniconda2/envs/pulsar/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/users/tcohen/miniconda2/envs/pulsar/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/users/tcohen/miniconda2/envs/pulsar/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/users/tcohen/python/projects/pyne2001/setup.py", line 34, in run
        compile_ne2001()
      File "/users/tcohen/python/projects/pyne2001/setup.py", line 17, in compile_ne2001
        subprocess.check_call('make all', shell=True)
      File "/users/tcohen/miniconda2/envs/pulsar/lib/python2.7/subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'make all' returned non-zero exit status 2
    ----------------------------------------
  ERROR: Can't roll back pyne2001; was not uninstalled
ERROR: Command errored out with exit status 1: /users/tcohen/miniconda2/envs/pulsar/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/users/tcohen/python/projects/pyne2001/setup.py'"'"'; __file__='"'"'/users/tcohen/python/projects/pyne2001/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
make: *** [install] Error 1
```

**Comment by v-morello** [comment] 2021-02-01 20:00
Hi Tyler,

We've seen that same situation before, can you check closed issue #1 ?

Let me know if the suggested solutions work for you,

**Comment by v-morello** [comment] 2021-02-05 09:07
@tycohen Did you manage to install it or are you still having issues ?

**Comment by tycohen** [comment] 2021-02-05 18:35
Yes, just needed to point it to gfortran. Thanks!

**Comment by v-morello** [comment] 2021-02-05 21:01
All right then, I am closing this.

**Comment by v-morello** [comment] 2021-02-05 21:03
Duplicate of #1

**Closed as completed by v-morello** 2021-02-05 21:03 UTC
Labels: duplicate
